version: "3.8"
services:
  app:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - .:/usr/src/app
    command: npm start
    networks:
      - app-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - app-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - app-net
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "secret"

networks:
  app-net:
    driver: bridge
