global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: "nodejs-app"
    static_configs:
      - targets: ["host.docker.internal:3000"] # Use 'localhost:3000' if Prometheus is not running in Docker
